-- CREATE TABLE ACCOUNT (ID BIGINT IDENTITY PRIMARY KEY, OWNER_NAME VARCHAR(255), BALANCE DOUBLE, ACCESS_TIME TIMESTAMP, LOCKED BOOLEAN);
CREATE TABLE USERS
(
  ID            NUMBER NOT NULL
    CONSTRAINT USERS_ID_PK
    PRIMARY KEY,
  FIRST_NAME    VARCHAR2(200),
  LAST_NAME     VARCHAR2(200),
  SALARY        NUMBER,
  DATE_OF_BIRTH DATE
);
create SEQUENCE seq_users INCREMENT BY 1 START WITH 100;